// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.wsc.proto;

import com.google.protobuf.AbstractMessageLite;

public final class Message {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Data_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Data_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rMessage.proto\"V\n\004Data\022\014\n\004code\030\001 \001(\005\022\017\n" +
                        "\007message\030\002 \001(\t\022\022\n\nserverName\030\003 \001(\t\022\014\n\004da" +
                        "ta\030\004 \001(\t\022\r\n\005async\030\005 \001(\010B\030\n\rbt.game.proto" +
                        "B\007Messageb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Data_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Data_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Data_descriptor,
                new String[]{"Code", "Message", "ServerName", "Data", "Async",});
    }

    private Message() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface DataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Data)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <pre>
         * 额外信息
         * </pre>
         *
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        String getMessage();

        /**
         * <pre>
         * 额外信息
         * </pre>
         *
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <pre>
         * 服务名
         * </pre>
         *
         * <code>string serverName = 3;</code>
         *
         * @return The serverName.
         */
        String getServerName();

        /**
         * <pre>
         * 服务名
         * </pre>
         *
         * <code>string serverName = 3;</code>
         *
         * @return The bytes for serverName.
         */
        com.google.protobuf.ByteString
        getServerNameBytes();

        /**
         * <pre>
         * 具体数据信息，一般用json包装
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The data.
         */
        String getData();

        /**
         * <pre>
         * 具体数据信息，一般用json包装
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The bytes for data.
         */
        com.google.protobuf.ByteString
        getDataBytes();

        /**
         * <pre>
         * 是否异步请求
         * </pre>
         *
         * <code>bool async = 5;</code>
         *
         * @return The async.
         */
        boolean getAsync();
    }

    /**
     * Protobuf type {@code Data}
     */
    public static final class Data extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Data)
            DataOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int MESSAGE_FIELD_NUMBER = 2;
        public static final int SERVERNAME_FIELD_NUMBER = 3;
        public static final int DATA_FIELD_NUMBER = 4;
        public static final int ASYNC_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Data)
        private static final Data DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Data>
                PARSER = new com.google.protobuf.AbstractParser<Data>() {
            @Override
            public Data parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new Data();
        }

        private int code_ = 0;
        @SuppressWarnings("serial")
        private volatile Object message_ = "";
        @SuppressWarnings("serial")
        private volatile Object serverName_ = "";
        @SuppressWarnings("serial")
        private volatile Object data_ = "";
        private boolean async_ = false;
        private byte memoizedIsInitialized = -1;

        // Use Data.newBuilder() to construct.
        private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Data() {
            message_ = "";
            serverName_ = "";
            data_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Message.internal_static_Data_descriptor;
        }

        public static Data parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Data parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Data prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Data getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Data> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new Data();
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Message.internal_static_Data_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Data.class, Builder.class);
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        /**
         * <pre>
         * 额外信息
         * </pre>
         *
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        @Override
        public String getMessage() {
            Object ref = message_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 额外信息
         * </pre>
         *
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        @Override
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 服务名
         * </pre>
         *
         * <code>string serverName = 3;</code>
         *
         * @return The serverName.
         */
        @Override
        public String getServerName() {
            Object ref = serverName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                serverName_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 服务名
         * </pre>
         *
         * <code>string serverName = 3;</code>
         *
         * @return The bytes for serverName.
         */
        @Override
        public com.google.protobuf.ByteString
        getServerNameBytes() {
            Object ref = serverName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                serverName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 具体数据信息，一般用json包装
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The data.
         */
        @Override
        public String getData() {
            Object ref = data_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                data_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 具体数据信息，一般用json包装
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The bytes for data.
         */
        @Override
        public com.google.protobuf.ByteString
        getDataBytes() {
            Object ref = data_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                data_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 是否异步请求
         * </pre>
         *
         * <code>bool async = 5;</code>
         *
         * @return The async.
         */
        @Override
        public boolean getAsync() {
            return async_;
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (code_ != 0) {
                output.writeInt32(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverName_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverName_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
            }
            if (async_ != false) {
                output.writeBool(5, async_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverName_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverName_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
            }
            if (async_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, async_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Data)) {
                return super.equals(obj);
            }
            Data other = (Data) obj;

            if (getCode()
                    != other.getCode()) return false;
            if (!getMessage()
                    .equals(other.getMessage())) return false;
            if (!getServerName()
                    .equals(other.getServerName())) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (getAsync()
                    != other.getAsync()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getServerName().hashCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (37 * hash) + ASYNC_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getAsync());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Data> getParserForType() {
            return PARSER;
        }

        @Override
        public Data getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Data}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Data)
                DataOrBuilder {
            private int bitField0_;
            private int code_;
            private Object message_ = "";
            private Object serverName_ = "";
            private Object data_ = "";
            private boolean async_;

            // Construct using bt.game.proto.Message.Data.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Message.internal_static_Data_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Message.internal_static_Data_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Data.class, Builder.class);
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = 0;
                message_ = "";
                serverName_ = "";
                data_ = "";
                async_ = false;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Message.internal_static_Data_descriptor;
            }

            @Override
            public Data getDefaultInstanceForType() {
                return Data.getDefaultInstance();
            }

            @Override
            public Data build() {
                Data result = buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Data buildPartial() {
                Data result = new Data(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(Data result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.message_ = message_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.serverName_ = serverName_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.data_ = data_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.async_ = async_;
                }
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Data) {
                    return mergeFrom((Data) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Data other) {
                if (other == Data.getDefaultInstance()) return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (!other.getServerName().isEmpty()) {
                    serverName_ = other.serverName_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (!other.getData().isEmpty()) {
                    data_ = other.data_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                if (other.getAsync() != false) {
                    setAsync(other.getAsync());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                code_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                message_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                serverName_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                data_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 40: {
                                async_ = input.readBool();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 40
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 code = 1;</code>
             *
             * @return The code.
             */
            @Override
            public int getCode() {
                return code_;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 额外信息
             * </pre>
             *
             * <code>string message = 2;</code>
             *
             * @return The message.
             */
            public String getMessage() {
                Object ref = message_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 额外信息
             * </pre>
             *
             * <code>string message = 2;</code>
             *
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                message_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 额外信息
             * </pre>
             *
             * <code>string message = 2;</code>
             *
             * @return The bytes for message.
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 额外信息
             * </pre>
             *
             * <code>string message = 2;</code>
             *
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                AbstractMessageLite.checkByteStringIsUtf8(value);
                message_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 额外信息
             * </pre>
             *
             * <code>string message = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessage() {
                message_ = getDefaultInstance().getMessage();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务名
             * </pre>
             *
             * <code>string serverName = 3;</code>
             *
             * @return The serverName.
             */
            public String getServerName() {
                Object ref = serverName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    serverName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 服务名
             * </pre>
             *
             * <code>string serverName = 3;</code>
             *
             * @param value The serverName to set.
             * @return This builder for chaining.
             */
            public Builder setServerName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                serverName_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务名
             * </pre>
             *
             * <code>string serverName = 3;</code>
             *
             * @return The bytes for serverName.
             */
            public com.google.protobuf.ByteString
            getServerNameBytes() {
                Object ref = serverName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    serverName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 服务名
             * </pre>
             *
             * <code>string serverName = 3;</code>
             *
             * @param value The bytes for serverName to set.
             * @return This builder for chaining.
             */
            public Builder setServerNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                AbstractMessageLite.checkByteStringIsUtf8(value);
                serverName_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务名
             * </pre>
             *
             * <code>string serverName = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearServerName() {
                serverName_ = getDefaultInstance().getServerName();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 具体数据信息，一般用json包装
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return The data.
             */
            public String getData() {
                Object ref = data_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    data_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 具体数据信息，一般用json包装
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 具体数据信息，一般用json包装
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return The bytes for data.
             */
            public com.google.protobuf.ByteString
            getDataBytes() {
                Object ref = data_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    data_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 具体数据信息，一般用json包装
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @param value The bytes for data to set.
             * @return This builder for chaining.
             */
            public Builder setDataBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                AbstractMessageLite.checkByteStringIsUtf8(value);
                data_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 具体数据信息，一般用json包装
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                data_ = getDefaultInstance().getData();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 是否异步请求
             * </pre>
             *
             * <code>bool async = 5;</code>
             *
             * @return The async.
             */
            @Override
            public boolean getAsync() {
                return async_;
            }

            /**
             * <pre>
             * 是否异步请求
             * </pre>
             *
             * <code>bool async = 5;</code>
             *
             * @param value The async to set.
             * @return This builder for chaining.
             */
            public Builder setAsync(boolean value) {

                async_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 是否异步请求
             * </pre>
             *
             * <code>bool async = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAsync() {
                bitField0_ = (bitField0_ & ~0x00000010);
                async_ = false;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Data)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
